config/routes.rb
Rails.application.routes.draw do
  
  root 'offers#new'
  resources :offers, only: [:new, :create, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
class Offer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
 
  def new
  	@offer = Offer.new
  end

  def create
  	@offer = Offer.new(buyer_title: params[:buyer_title],
  										 buyer_first_name: params[:offer][:buyer_first_name],
  										 buyer_last_name: params[:offer][:buyer_last_name],
  										 buyer_email: params[:offer][:buyer_email],
  										 buyer_adress: params[:offer][:buyer_adress],
  										 buyer_zipcode: params[:offer][:buyer_zipcode],
  										 buyer_city: params[:offer][:buyer_city],
  										 seller_title: params[:seller_title],
  										 seller_first_name: params[:offer][:seller_first_name],
  										 seller_last_name: params[:offer][:seller_last_name],
  										 seller_adress: params[:offer][:seller_adress],
  										 seller_zipcode: params[:offer][:seller_zipcode],
  										 seller_city: params[:offer][:seller_city],
  										 property_adress: params[:offer][:property_adress],
  										 property_zipcode: params[:offer][:property_zipcode],
  										 property_city: params[:offer][:property_city],
  										 property_type: params[:property_type],
  										 property_surface: params[:offer][:property_surface],
  										 property_price: params[:offer][:property_price],
  										 property_price_letters: params[:offer][:property_price_letters],
  										 date_max:params[:year]+"-"+params[:month]+"-"+params[:day]
  										)
  	if @offer.save
      redirect_to offer_path(@offer, format: :pdf)
    else 
    	render "new"
    end
  end

  def show
    @offer = Offer.find(params[:id])

    respond_to do |format|
        format.html
        format.pdf do
            render pdf: "Offre_#{@offer.buyer_last_name}_#{@offer.created_at.strftime("%Y-%m-%d")}",
            page_size: 'A4',
            template: "offers/show.html.erb",
            orientation: "Portrait",
            lowquality: true,
            zoom: 1,
            dpi: 75
        end
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>SuperPlume</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css"> 

      <!-- Mobile Specific Metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>

</html>

app/views/offers/new.html.erb
<div class="page-content">
    <div class="wizard-v5-content">
      <div class="wizard-form">

            <%= form_with model: @offer, url: offers_path, local: true,  html: {id: "form-register", class: "form-register"} do |f| %>


              <div id="form-total">
                <!-- SECTION 1 -->
                  <h2>
                    <span class="step-icon"><i class="zmdi zmdi-check"></i></span>
                    <span class="step-text">Les coordonnées</span>
                  </h2>
            
            <section>   
              <div class="inner">
                <!-- BUYER -->
                <h3>Coordonnées de l'acheteur</h3>

                <div class="form-row">
                  <div id="radio">
                    <label for="gender">Titre :</label>
                      <%= radio_button_tag(:buyer_title, "Monsieur", :checked => 'true') %>Monsieur
                      <%= radio_button_tag(:buyer_title, "Madame") %>Madame
                      <%= radio_button_tag(:buyer_title, "Mademoiselle") %>Mademoiselle
                  </div>
                </div>

                <div class="form-row">
                  <div class="form-holder">
                    <label for="first_name">Prénom</label>
                    <%= f.text_field :buyer_first_name, class: 'form-control', placeholder:"ex: Patricia" %>
                  </div>
                  <div class="form-holder">
                    <label for="last_name">Nom</label>
                    <%= f.text_field :buyer_last_name, class: 'form-control', placeholder:"ex: Dubois" %>
                  </div>
                </div>

                <div class="form-row">
                  <div class="form-holder form-holder-2">
                    <label for="adress">Email</label>
                    <%= f.text_field :buyer_email, class: 'form-control', placeholder:"ex: patricia@email.com" %>
                  </div>
                </div>

                 <div class="form-row">
                  <div class="form-holder form-holder-2">
                    <label for="adress">Adresse de l'acheteur</label>
                    <%= f.text_field :buyer_adress, class: 'form-control', placeholder:"ex: 12 rue des Rosiers" %>
                    <span><i class="zmdi zmdi-pin"></i></span>
                  </div>
                </div>
                <div class="form-row">
                  <div class="form-holder form-holder-3">
                    <label for="phone">Ville</label>
                    <%= f.text_field :buyer_city, class: 'form-control', placeholder:"ex: Orléans" %>
                  </div>
                  <div class="form-holder">
                    <label for="code">Code postal</label>
                    <%= f.text_field :buyer_zipcode, class: 'form-control' %>
                  </div>
                </div>

                <!-- SELLER -->
                <br>
                <h3>Coordonnées du vendeur</h3>

                <div class="form-row">
                  <div id="radio">
                    <label for="gender">Titre :</label>
                      <%= radio_button_tag(:seller_title, "Monsieur",:checked => 'true') %>Monsieur
                      <%= radio_button_tag(:seller_title, "Madame") %>Madame
                      <%= radio_button_tag(:seller_title, "Mademoiselle") %>Mademoiselle
                  </div>
                </div>

                <div class="form-row">
                  <div class="form-holder">
                    <label for="first_name">Prénom</label>
                    <%= f.text_field :seller_first_name, class: 'form-control', placeholder:"ex: Patricia" %>
                  </div>
                  <div class="form-holder">
                    <label for="last_name">Nom</label>
                    <%= f.text_field :seller_last_name, class: 'form-control', placeholder:"ex: Dubois" %>
                  </div>
                </div>

                 <div class="form-row">
                  <div class="form-holder form-holder-2">
                    <label for="adress">Adresse du vendeur</label>
                    <%= f.text_field :seller_adress, class: 'form-control', placeholder:"ex: 12 rue des Rosiers" %>
                    <span><i class="zmdi zmdi-pin"></i></span>
                  </div>
                </div>
                <div class="form-row">
                  <div class="form-holder form-holder-3">
                    <label for="phone">Ville</label>
                    <%= f.text_field :seller_city, class: 'form-control', placeholder:"ex: Orléans" %>
                  </div>
                  <div class="form-holder">
                    <label for="code">Code postal</label>
                    <%= f.text_field :seller_zipcode, class: 'form-control' %>
                  </div>
                </div>               



              </div>
                  </section>

            <!-- SECTION 2 -->
                  <h2>
                    <span class="step-icon"><i class="zmdi zmdi-check"></i></span>
                    <span class="step-text">Le bien</span>
                  </h2>
                  <section>

                      <div class="inner">
                        <h3>Description du bien</h3>

              <div class="form-row">
                  <div id="radio">
                    <label for="gender">Type :</label>
                      <%= radio_button_tag(:property_type, "Maison",:checked => 'true') %>Maison
                      <%= radio_button_tag(:property_type, "Loft") %>Loft
                      <%= radio_button_tag(:property_type, "Studio") %>Studio
                      <%= radio_button_tag(:property_type, "T2") %>T2
                      <%= radio_button_tag(:property_type, "T3") %>T3
                      <%= radio_button_tag(:property_type, "T4") %>T4
                      <%= radio_button_tag(:property_type, "T5") %>T5
                  </div>
                </div>

                <div class="form-row">
                  <div class="form-holder form-holder-2">
                    <label for="adress">Adresse du bien</label>
                    <%= f.text_field :property_adress, class: 'form-control', placeholder:"ex: 12 rue des Rosiers" %>
                    <span><i class="zmdi zmdi-pin"></i></span>
                  </div>
                </div>
                <div class="form-row">
                  <div class="form-holder form-holder-3">
                    <label for="phone">Ville</label>
                    <%= f.text_field :property_city, class: 'form-control', placeholder:"ex: Orléans" %>
                  </div>
                  <div class="form-holder">
                    <label for="code">Code postal</label>
                    <%= f.text_field :property_zipcode, class: 'form-control' %>
                  </div>
                </div> 

                <div class="form-row">
                  <div class="form-holder form-holder-3">
                    <label for="phone">Surface (en m²)</label>
                    <%= f.text_field :property_surface, class: 'form-control'%>
                      <span>m²</span>
                  </div>
                  <div class="form-holder">
                    <label for="code">Prix d'achat (en nombre)</label>
                    <%= f.text_field :property_price, class: 'form-control' %>
                      <span>€</span>
                  </div>
                </div> 

                <div class="form-row">
                  <div class="form-holder form-holder-2">
                    <label for="account_number">Prix d'achat (en toutes lettres)</label>
                    <%= f.text_field :property_price_letters, class: 'form-control' %>
                  </div>
                </div>
                <div class="form-row form-row-date form-row-step-2">
                  <div class="form-holder form-holder-2">
                    <label for="date_2" class="special-label">Expiration de l'offre</label>
                    
                    <%= select_tag 'day', options_for_select([*01..31].collect{ |d| [d, d] }), class:"form-control" %>

                    <%= select_tag 'month', options_for_select(%w(Janvier Février Mars Avril Mai Juin Juillet Août Septembre Octobre Novembre Décembre).map.with_index{ |m, i| [m, i+1] }), class:"form-control" %>

                    <%= select_tag 'year', options_for_select(%w(2020 2021 2022).collect{ |y| [y, y] }), class:"form-control" %>
                    
                  </div>
                </div>
              </div>
                  </section>
                  <!-- SECTION 3 -->
                  <h2>
                    <span class="step-icon"><i class="zmdi zmdi-check"></i></span>
                    <span class="step-text">Confirmation</span>
                  </h2>
                  <section>
                      <div class="inner">
                        <h3>Récapitulatif des informations</h3>
                <div class="form-row table-responsive">
                  <table class="table">
                    <tbody>
                      <tr class="space-row">
                        <th>Acheteur</th>
                        <td id="buyer_fullname-val"></td>
                      </tr>
                      <tr class="space-row">
                        <th>Email de l'acheteur</th>
                        <td id="buyer_email-val"></td>
                      </tr>
                      <tr class="space-row">
                        <th>Adresse de l'acheteur</th>
                        <td id="buyer_adress-val"></td>
                      </tr>                      
                      <tr class="space-row">
                        <th>Vendeur</th>
                        <td id="seller_fullname-val"></td>
                      </tr>
                      <tr class="space-row">
                        <th>Adresse du vendeur</th>
                        <td id="seller_adress-val"></td>
                      </tr>
                      <tr class="space-row">
                        <th>Description du bien</th>
                        <td id="property_description-val"></td>
                      </tr>
                      <tr class="space-row">
                        <th>Adresse du bien</th>
                        <td id="property_adress-val"></td>
                      </tr>
                      <tr class="space-row">
                        <th>Prix du bien</th>
                        <td id="property_price-val"></td>
                      </tr>
                      <tr class="space-row">
                        <th>Date limite de l'offre</th>
                        <td id="date_max-val"></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>

            <center>
              <%= f.submit "Télécharger ma lettre d'offre", :class => 'submit-btn'%>
              <% end %>
            </center>

                  </section>
              </div>

      </div>
    </div>
  </div>

app/views/offers/show.html.erb
<!DOCTYPE html>
<html>
<meta charset="UTF-8">
<head>
<title>Super-plume_Lettre d'offre_PDF</title>
</head>
<body>

<div style="padding:40px;background-color:#FFFFFF; margin :0 auto;color:#000000;"> 
	<table width="100%" cellspacing="0" cellpadding="6" border="0"> 
		<tbody>
			<tr> 
				<td>
					<table width="100%"> 
		<tbody>
			<tr> 
				<td width="55%"><font size="3" face="Verdana"><%=@offer.buyer_title%> <%=@offer.buyer_first_name%> <%=@offer.buyer_last_name %>
					<br> <%=@offer.buyer_adress%> 
					<br> <%=@offer.buyer_zipcode%> <%=@offer.buyer_city%>
					<br> <%=@offer.buyer_email%></font><br>
				</td> 
				<td>&nbsp;</td> 
			</tr> 
			<tr> 
				<td width="55%">&nbsp;</td> 
				<td><font size="3" face="Verdana"><%=@offer.seller_title%> <%=@offer.seller_first_name%> <%=@offer.seller_last_name %>
 					<br> <%=@offer.seller_adress%> 
					<br> <%=@offer.seller_zipcode%> <%=@offer.seller_city%> <br>
				</td> 
			</tr> 
			<tr> 
				<td width="55%">&nbsp;</td> 
				<td>&nbsp;</td> 
			</tr> 
		</tbody>
	</table>
<br><br>
<br><br>
					<p><font size="3" face="Verdana"><b>Objet : Proposition d’achat du bien situé au <%=@offer.property_adress%>, <%=@offer.property_zipcode%> <%=@offer.property_city%></b></font></p><br>
					<p><font size="3" face="Verdana"><%=@offer.seller_title%>,</font></p>
					<p><font size="3" face="Verdana">À la date du <%=@offer.created_at.strftime("%d/%m/%Y")%>, <%=@offer.buyer_title%> <%=@offer.buyer_last_name%> demande à acquérir, en cas d’acceptation de la présente offre, de façon ferme et irrévocable, le bien désigné ci-dessous :
					</font></p>
					<p><font size="3" face="Verdana">Type de bien : <%=@offer.property_type%> </font></p>
					<p><font size="3" face="Verdana">Adresse: <%=@offer.property_adress%>, <%=@offer.property_zipcode%> <%=@offer.property_city%></font></p>
					<p><font size="3" face="Verdana">Superficie : <%=@offer.property_surface%> m² loi Carrez</font></p>
					<p><font size="3" face="Verdana">Prix : <%=@offer.property_price%> € (<%=@offer.property_price_letters%>) </font></p>
					<p><font size="3" face="Verdana">Ainsi, je vous propose d’acheter ce bien au prix de <%=@offer.property_price%> € (<%=@offer.property_price_letters%>), hors frais de notaire, hors frais d’agence, qui sera payé intégralement le jour de la signature de l’acte authentique de vente.</font></p>
					<p><font size="3" face="Verdana">La présente offre d’achat est faite à <%=@offer.seller_title%> <%=@offer.seller_last_name%>.</font></p>
					<p><font size="3" face="Verdana">
					En l’absence d’acceptation de la présente offre d’achat, celle-ci s’éteindra le <%=@offer.date_max.strftime("%d/%m/%Y")%>.</font></p>
					<p><font size="3" face="Verdana">L’acceptation du Vendeur pourra être formulée par tout moyen au domicile du Promettant ci-dessus désigné.</font></p>
					<br>

					<p><font size="3" face="Verdana">Le <%=@offer.created_at.strftime("%d/%m/%Y")%>,</font></p>
					<br>
					<p><font size="3" face="Verdana">Signature :<br> <br> </font></p> 
				</td> 
			</tr> 
		</tbody>
	</table> 
</div>

</body>
</html>